#!/usr/bin/env python3
"""
Build the @shavitness Instagram Remodel spec, a single, portable, self-contained
HTML file Jake grills and then shows Shavit. Every image is embedded ONCE as a
base64-backed CSS class (.bg-<key>) and referenced by class, so reusing an image
across the profile mockup AND the week-by-week strip costs no extra file size.
Brand = the live shavitrootman.com system (black canvas, brass #B08D57, gold
#FFC000, Inter uppercase), presented as an Instagram dark-mode profile.
"""
import base64, pathlib, sys

ROOT = pathlib.Path(__file__).parent
TILES_DIR = ROOT / "assets" / "tiles"
OUT = ROOT / "index.html"

def datauri(p: pathlib.Path) -> str:
    if not p.exists():
        print(f"WARN missing {p}", file=sys.stderr)
        return ""
    mime = "image/jpeg" if p.suffix.lower() in (".jpg", ".jpeg") else "image/png"
    return f"data:{mime};base64," + base64.b64encode(p.read_bytes()).decode()

# ---- every image, embedded once, keyed --------------------------------------
KEYS = ["reel1","reel2","riverst","eaststjoe","larchmere","salem","riverst_cap",
        "eaststjoe_cap","longform1","longform2","ph_river","ph_larchmere","ph_mead",
        "ph_clevehts","ph_secondchance","ph_westside",
        # social cover art, generated by build_banner.py
        "cover_fb","cover_li"]
IMAGES = {k: datauri(TILES_DIR / f"{k}.jpg") for k in KEYS}
IMAGES["avatar"] = datauri(ROOT / "assets" / "avatar.jpeg")
CSS_IMG = "\n".join(f".bg-{k}{{background-image:url('{u}')}}" for k, u in IMAGES.items() if u)

# ---- icons ------------------------------------------------------------------
REEL_SVG = ('<svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="#fff" '
            'stroke-width="1.8" stroke-linejoin="round"><rect x="2" y="2" width="20" height="20" rx="5"/>'
            '<path d="M2 8h20M8 2l2.5 6M14 2l2.5 6"/><path d="M10.5 11.5v5l4-2.5z" fill="#fff" stroke="none"/></svg>')
CAROUSEL_SVG = ('<svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="#fff" '
                'stroke-width="1.8"><rect x="7" y="3" width="14" height="14" rx="3"/>'
                '<path d="M4 7v11a3 3 0 0 0 3 3h11"/></svg>')
ICON = {"reel": REEL_SVG, "carousel": CAROUSEL_SVG, "photo": ""}

# ---- main grid tiles (mix of reels + house photos) --------------------------
GRID_TILES = [
    dict(key="longform1",    icon="reel",    badge="BRAND FILM", pin=True, ba=True, cap="Reel, manifesto: “Most see a write-off. We see a home.”"),
    dict(key="reel2",        icon="reel",    badge="PORTFOLIO", pin=True, ba=False, cap="Reel, inside the portfolio, three states, one operator"),
    dict(key="riverst_cap",  icon="reel",    badge=None,        pin=True, ba=True, cap="Reel, River Street, Hillsdale: before → after"),
    dict(key="ph_mead",      icon="carousel", badge="PHOTOS",    pin=False, ba=False, cap="Photo carousel, 34 Mead St, before & after stills"),
    dict(key="eaststjoe",    icon="reel",    badge=None,        pin=False, ba=True, cap="Reel, East St. Joe: “the different ending”"),
    dict(key="ph_larchmere", icon="carousel", badge="PHOTOS",    pin=False, ba=False, cap="Photo carousel, Larchmere Duplex, room by room"),
    dict(key="salem",        icon="reel",    badge="SPLIT",     pin=False, ba=True, cap="Reel, 61 Salem St, split-screen"),
    dict(key="ph_clevehts",  icon="carousel", badge="PHOTOS",    pin=False, ba=False, cap="Photo carousel, Cleveland Heights, exterior restored"),
    dict(key="larchmere",    icon="reel",    badge="SHOWCASE",  pin=False, ba=False, cap="Reel, Larchmere showcase walk-through"),
    dict(key="ph_secondchance",icon="carousel",badge="PHOTOS",    pin=False, ba=False, cap="Photo carousel, Second-Chance Ranch, the mission"),
    dict(key="eaststjoe_cap",icon="reel",    badge="INSIDE",    pin=False, ba=True, cap="Reel, East St. Joe: same house, rebuilt"),
    dict(key="ph_westside",  icon="photo",   badge=None,        pin=False, ba=False, cap="Photo, West Side Cleveland, one step at a time"),
]

def tile_html(d):
    pin = '<span class="pin">📌</span>' if d["pin"] else ''
    badge = f'<span class="tbadge">{d["badge"]}</span>' if d["badge"] else ''
    ba = '<span class="ba">BEFORE · AFTER</span>' if d["ba"] else ''
    return f'''<figure class="tile bg-{d['key']}" title="{d['cap']}">
      <span class="ticon">{ICON[d['icon']]}</span>{pin}{badge}{ba}
      <figcaption>{d['cap']}</figcaption>
    </figure>'''

GRID = "\n".join(tile_html(d) for d in GRID_TILES)

# ---- highlights -------------------------------------------------------------
HL = [
    ("ON FILM", "longform1", "The reels. Brand film first, then every cinematic cut. A stranger taps here to see the operation move."),
    ("HOUSES", "ph_larchmere", "The photos. Finished rooms and finished homes, the way they look the day someone moves in."),
    ("THE WORK", "salem", "The renovations. Studs, dust, and the reveal. Shot on a phone, straight from the job site."),
    ("ROOTS", "avatar", "The human thread, Shavit, the Rootman clan, Israel. Kept and re-homed here (not scrubbed): authenticity the 5k base already follows him for."),
    ("AVAILABLE", "ph_mead", "What’s available, and how to reach him. The only highlight that asks for anything."),
]
HL_HTML = "\n".join(
    f'''<div class="hl">
      <div class="hl-ring"><span class="hl-cover bg-{key}"></span></div>
      <div class="hl-name">{name}</div>
      <p class="hl-desc">{desc}</p>
    </div>''' for name, key, desc in HL)
HL_ROW = "\n".join(
    f'''<div class="phl"><span class="phl-ring"><span class="phl-cover bg-{key}"></span></span>
      <span class="phl-label">{name.replace(" 🇮🇱","")}</span></div>''' for name, key, desc in HL)

# ---- CROSS-PLATFORM: every social, current -> revised ------------------------
# All four accounts already exist (verified live). Each is a public before/after.
PLATFORMS = [
    dict(mark="IG", tint="#B08D57", name="Instagram", handle="@shavitness",
         url="instagram.com/shavitness", role="Flagship grid",
         now="Personal account · bare Hebrew bio · dormant since Feb · 2023 pins on top",
         rev="Live with us. Work with us.\n📍 Midwest ᐧ 3 states\n👇 The before and after\n🔗 shavitrootman.com/links",
         note="The full remodel above. Business account, re-pinned to brand film + flagship before/afters. 5,054-follower base reactivated on 2-3 posts/week."),
    dict(mark="f", tint="#1877F2", name="Facebook Page", handle="@shavitrootman",
         url="facebook.com/shavit.rootman", role="Reputation hub",
         now="A personal profile (facebook.com/shavit.rootman), login-gated, mixed personal, no brand, no category, can’t be scheduled or measured.",
         rev="Shavit Rootman · Property Management Company\n\nLive with us. Work with us.\n\nWe rebuild what other people wrote off. We buy,\nwe restore, and then we stay. Across three states, every project documented before → after.",
         note="Stand up a proper Business Page (keep the personal profile as-is). The Page is what Meta Business Suite can schedule, categorize, and pull Insights from, a personal profile can’t. Pinned post = the brand film."),
    dict(mark="◱", tint="#FFC000", name="Meta Business Suite", handle="the cockpit",
         url="business.facebook.com", role="The engine",
         now="Not connected. FB and IG are posted to by hand, one app at a time, with no shared queue and no unified numbers.",
         rev="One control panel over the new FB Page + Instagram:\n• schedule both at once, 1-2 weeks ahead\n• one content queue, one unified inbox\n• Insights export → straight into the scorecard",
         note="This is what makes 2-3 posts/week across two platforms a ~30-min/week job instead of a daily chore. It’s the reliability moat, automated. Requires the FB Business Page above to exist first."),
    dict(mark="in", tint="#0A66C2", name="LinkedIn", handle="/in/shavitrootman",
         url="linkedin.com/in/shavitrootman", role="The operator’s room",
         now="“Founder, Charger Property Management,” Santa Barbara framing, older personal/job-seeking posts. 500+ connections, but reads as a résumé, not an operator brand.",
         rev="HEADLINE\nFounder, Charger Property Management · Rebuilding\nacross three states\n\nABOUT (opening)\nWe buy what everyone else passed on, rebuild to a\nstandard we’d live in ourselves, and manage like we\nintend to keep it. Across three states, Michigan, Ohio, and Indiana.",
         note="Keep it personal, it’s his profile, not a company page. Point it at the brand: new headline, Featured section = brand film + top before/afters. GUARDRAIL: portfolio & reputation only, never a public “invest with me” ask (Reg D solicitation risk)."),
    dict(mark="S", tint="#FF6719", name="Substack", handle="shavitrootman.substack.com",
         url="shavitrootman.substack.com", role="The long-form notebook",
         now="Already live: “Community Impact Made Profitable” / “From Special Forces in Israel to Pursuing Truth in Hillsdale.” Today it’s a personal & political journal, not the real-estate brand.",
         rev="Community Impact Made Profitable\nNotes from rebuilding what other people wrote off.\n\nOne project a month, start to finish, what we bought,\nwhat we found in the walls, what it cost, what it became.\nOnce a month. No pitches.",
         note="Reposition, don’t replace. Keep the “Community Impact Made Profitable” line, it already fits the second-chance-housing mission, and aim it at monthly project deep-dives. The Israel/personal thread stays as its own section, not the whole publication."),
]
def platform_card(p):
    return f'''<div class="pcard">
      <div class="pcard-head">
        <span class="picon" style="background:{p['tint']}">{p['mark']}</span>
        <div class="pcard-id"><b>{p['name']}</b><span class="purl">{p['url']}</span></div>
        <span class="prole">{p['role']}</span>
      </div>
      <div class="pcompare">
        <div class="pbox pnow"><div class="plbl">Now</div><div class="pcode">{p['now']}</div></div>
        <div class="pbox prev"><div class="plbl">Revised</div><div class="pcode">{p['rev']}</div></div>
      </div>
      <p class="pnote">{p['note']}</p>
    </div>'''
PLATFORMS_HTML = "\n".join(platform_card(p) for p in PLATFORMS)

# ---- per-platform VISUAL mockups (same phone treatment as Instagram) --------
NOTCH = ('<div class="notch"><span>9:41</span><span class="dot"></span>'
         '<span>&#9679;&#9679;&#9679; &#9207; &#9635;</span></div>')

def pstage(mock_inner, role, now, rev, note):
    return f'''<div class="pstage">
      <div class="phone">{NOTCH}<div class="mock">{mock_inner}</div></div>
      <div class="notes">
        <div class="note"><h4><span class="tag">Now</span> {role}</h4><p>{now}</p></div>
        <div class="note"><h4><span class="tag" style="background:var(--gold);color:#000">Revised</span> What changes</h4><p>{rev}</p></div>
        <div class="callout">{note}</div>
      </div>
    </div>'''

FB_MOCK = f'''
  <div class="m-cover bg-cover_fb"></div>
  <div class="m-ava bg-avatar"></div>
  <div class="m-body">
    <div class="m-name">Shavit Rootman</div>
    <div class="m-sub">Property Management Company · New Page</div>
    <div class="m-meta">📍 Midwest · 3 states</div>
    <div class="m-btns"><button style="background:#1877F2">+ Follow</button>
      <button class="ghost">Message</button><button class="ghost">✉</button></div>
    <div class="m-card"><div class="h">Intro</div>Live with us. Work with us.

We rebuild what other people wrote off. We buy, we restore, and then we stay. Across three states, every project documented before → after.
<span class="m-lk">🔗 shavitrootman.com/links</span></div>
    <div class="m-tabs"><span class="on">Posts</span><span>About</span><span>Photos</span><span>More</span></div>
    <div class="m-pin"><span class="m-thumb bg-riverst"></span>
      <div class="t"><b>📌 Pinned · River Street, Hillsdale</b><br><span>Before → after. “We took a solid home and made it something special.”</span></div></div>
  </div>'''

LI_MOCK = f'''
  <div class="m-cover bg-cover_li"></div>
  <div class="m-ava bg-avatar"></div>
  <div class="m-body">
    <div class="m-name">Shavit Rootman</div>
    <div class="m-sub" style="color:#eaeaea;font-weight:600">Founder, Charger Property Management · Rebuilding across three states</div>
    <div class="m-meta">Santa Barbara, CA · 500+ connections</div>
    <div class="m-btns"><button style="background:#0A66C2">Connect</button>
      <button class="ghost">Message</button><button class="ghost">More</button></div>
    <div class="m-card"><div class="h">About</div>We buy what everyone else passed on, rebuild to a standard we’d live in ourselves, and manage like we intend to keep it. Across three states, bought direct, restored in-house, held not flipped.</div>
    <div class="m-card"><div class="h">Featured</div>
      <div class="m-feat">
        <div class="f bg-longform2"><span>▶ Brand film</span></div>
        <div class="f bg-riverst"><span>Before → after</span></div>
        <div class="f bg-ph_mead"><span>34 Mead St</span></div>
      </div></div>
  </div>'''

MBS_MOCK = f'''
  <div class="mbs">
    <div class="mbs-h"><span class="g">◱</span>Meta Business Suite</div>
    <div class="m-sub">One cockpit over both public accounts</div>
    <div class="mbs-conn"><span class="mbs-chip">f Shavit Rootman</span><span class="mbs-chip">◎ @shavitness</span></div>
    <div class="mbs-lbl">Scheduled, this week</div>
    <div class="mbs-row"><span class="th bg-riverst"></span><div class="mid"><b>River Street, before/after</b><span>Mon 9:00 AM · FB + IG</span></div><span class="st">Scheduled</span></div>
    <div class="mbs-row"><span class="th bg-ph_larchmere"></span><div class="mid"><b>Larchmere duplex, room by room</b><span>Wed 12:00 PM · FB + IG</span></div><span class="st">Scheduled</span></div>
    <div class="mbs-row"><span class="th bg-ph_secondchance"></span><div class="mid"><b>Second-chance housing, the mission</b><span>Fri 5:00 PM · FB + IG</span></div><span class="st">Scheduled</span></div>
    <div class="mbs-lbl">Insights, last 28 days</div>
    <div class="mbs-kpi"><div><b>Reach</b><span>tracked</span></div><div><b>Saves</b><span>tracked</span></div><div><b>Inbound</b><span>logged</span></div></div>
  </div>'''

SUB_MOCK = f'''
  <div class="sub-mast">
    <div class="sub-logo bg-avatar"></div>
    <div class="sub-title">Community Impact Made Profitable</div>
    <div class="sub-desc">Notes from rebuilding what other people wrote off.</div>
    <button class="sub-btn">Subscribe</button>
    <div class="sub-nav"><span>Home</span><span>Archive</span><span>About</span></div>
  </div>
  <div class="sub-post"><div class="body"><div class="ttl">34 Mead Street: the $57,500 house that fought us</div>
    <div class="dek">A woman in crisis, a clean exit, and eight weeks of everything the walls were hiding.</div><div class="dt">Monthly · 8 min read</div></div>
    <span class="th bg-ph_mead"></span></div>
  <div class="sub-post"><div class="body"><div class="ttl">River Street, Hillsdale: what “built to hold” actually costs</div>
    <div class="dek">We could’ve flipped it fast and cheap. Here’s what we did instead, line by line.</div><div class="dt">Monthly · 6 min read</div></div>
    <span class="th bg-riverst"></span></div>
  <div class="sub-post"><div class="body"><div class="ttl">South Bend, bought at auction, sight unseen</div>
    <div class="dek">No walkthrough, no guarantees, foreclosure to rented-and-thriving.</div><div class="dt">Monthly · 7 min read</div></div>
    <span class="th bg-eaststjoe"></span></div>'''

YT_MOCK = f'''
  <div class="m-cover bg-larchmere"></div>
  <div class="m-ava bg-avatar" style="margin-left:auto;margin-right:auto"></div>
  <div class="m-body" style="text-align:center">
    <div class="m-name" style="justify-content:center">Shavit Rootman</div>
    <div class="m-sub">@shavitrootman · Channel to establish</div>
    <div class="m-meta">Property transformation across three states</div>
    <button class="yt-subbtn">Subscribe</button>
  </div>
  <div class="m-tabs"><span class="on">Home</span><span>Videos</span><span>Shorts</span><span>About</span></div>
  <div class="yt-grid">
    <div class="yt-vid"><div class="thm bg-longform2"><span class="dur">1:02</span></div>
      <div class="vt">Live with us. Work with us. (the brand film)</div><div class="vm">Signature · pinned</div></div>
    <div class="yt-vid"><div class="thm bg-riverst"><span class="dur">4:10</span></div>
      <div class="vt">River Street, Hillsdale: the full rebuild</div><div class="vm">Before &amp; after tour</div></div>
    <div class="yt-vid"><div class="thm bg-ph_mead"><span class="dur">5:36</span></div>
      <div class="vt">34 Mead Street: the $57,500 house</div><div class="vm">Project deep-dive</div></div>
    <div class="yt-vid"><div class="thm bg-eaststjoe"><span class="dur">4:52</span></div>
      <div class="vt">South Bend, bought at auction, sight unseen</div><div class="vm">Before &amp; after tour</div></div>
  </div>'''

MOCKUPS_HTML = (
    pstage(FB_MOCK, "Facebook, a personal profile",
        "Today it’s <b class=\"white\">facebook.com/shavit.rootman</b>, a personal profile, login-gated, mixed personal, no category, and it <b class=\"white\">can’t be scheduled or measured</b>.",
        "Stand up a proper <b class=\"white\">Business Page</b>: category, cover, the locked intro copy, and a pinned brand film. A Page is the only thing Meta Business Suite can automate and pull Insights from.",
        "Keep the personal profile as-is, this is a <b>new Page</b> beside it, not a replacement.")
    + pstage(LI_MOCK, "LinkedIn, reads like a résumé",
        "<b class=\"white\">linkedin.com/in/shavitrootman</b>, “Founder, Charger Property Management,” older personal / job-seeking posts. 500+ connections, but it doesn’t say what the operation <i>is</i>.",
        "New <b class=\"white\">headline</b> and <b class=\"white\">About</b> aimed at the brand, a <b class=\"white\">Featured</b> row (brand film + top before/afters). Stays personal, it’s his profile, not a company page. It <b class=\"white\">relaunches with an announcement post</b>, drafted in full in the launch plan (Section 07).",
        "This is the exciting one: LinkedIn is where the operator audience lives, so the rebrand goes out loud here. GUARDRAIL: portfolio &amp; reputation only, never a public “invest with me” ask (Reg&nbsp;D solicitation risk).")
    + pstage(MBS_MOCK, "Meta Business Suite, not connected",
        "FB and IG are posted to <b class=\"white\">by hand, one app at a time</b>, no shared queue, no unified numbers, no buffer against a quiet week.",
        "One control panel over the new FB Page + Instagram: <b class=\"white\">schedule both at once</b> 1-2 weeks ahead, one inbox, and an Insights export that drops straight into the scorecard.",
        "This is what makes 2-3 posts/week across two platforms a <b>~30-min/week</b> job. The reliability moat, automated. Needs the FB Page above to exist first.")
    + pstage(SUB_MOCK, "Substack, already live, off-brand",
        "<b class=\"white\">shavitrootman.substack.com</b> exists as “Community Impact Made Profitable”, today a personal &amp; Israel/Hillsdale journal, not the real-estate brand.",
        "<b class=\"white\">Reposition, don’t replace.</b> Keep the “Community Impact Made Profitable” line (it fits the second-chance mission) and aim it at <b class=\"white\">one project deep-dive a month</b>.",
        "The Israel/personal thread stays as its own section, honored, not scrubbed, just no longer the whole publication.")
    + pstage(YT_MOCK, "YouTube, not established yet",
        "There’s no channel today. The value prop already names YouTube as a home for the signature film alongside IG and TikTok, right now that home doesn’t exist.",
        "Establish the channel as the <b class=\"white\">long-form house</b>: the brand film pinned, plus full before/after <b class=\"white\">project tours</b> that don’t fit in a 60-second reel. The one place the whole story runs start to finish.",
        "Lowest urgency of the six, stand it up when the first long cut is ready. Until then it holds the brand film and the handle, so the name is claimed.")
)

# ---- WEEK-BY-WEEK strip -----------------------------------------------------
# tile spec: ('new', key, badge, pin, ba) | ('old', label) | ('pinold', label)
def mini_tile(spec):
    kind = spec[0]
    if kind in ("old", "pinold"):
        label = spec[1]
        tag = '<span class="mpin">📌</span>' if kind == "pinold" else ''
        return f'<span class="mtile mold">{tag}<span class="moldlab">{label}</span></span>'
    _, key, badge, pin, ba = spec
    pins = '<span class="mpin">📌</span>' if pin else ''
    b = f'<span class="mbadge">{badge}</span>' if badge else ''
    baw = '<span class="mba"></span>' if ba else ''
    return f'<span class="mtile bg-{key}">{pins}{b}{baw}</span>'

def N(key, badge=None, pin=False, ba=False): return ("new", key, badge, pin, ba)
def O(label="post"): return ("old", label)
def OP(label): return ("pinold", label)

WEEKS = [
    dict(tag="TODAY", count="57 posts", tone="now",
         tiles=[OP("🇮🇱 2023"), OP("👪 Family"), O("before/after"),
                O("carousel"), O("before/after"), O("low-qual"),
                O("carousel"), O("before/after"), O("2024 post")],
         cap="Personal posts pinned on top. Last active February. Mixed quality, no through-line, reads dormant."),
    dict(tag="WEEK 2", count="60 posts", tone="go",
         tiles=[N("longform1","FILM",pin=True), N("reel2","PORTFOLIO",pin=True), N("riverst_cap",pin=True,ba=True),
                O("before/after"), O("carousel"), O("before/after"),
                O("carousel"), O("low-qual"), O("2024 post")],
         cap="Relaunch: 3 hero posts up & pinned, new bio + highlights live. The 2023 pins move to the “Roots” highlight. Nothing deleted."),
    dict(tag="WEEK 4", count="64 posts", tone="go",
         tiles=[N("longform1","FILM",pin=True), N("reel2","PORTFOLIO",pin=True), N("riverst_cap",pin=True,ba=True),
                N("ph_clevehts","PHOTOS"), N("eaststjoe",ba=True), N("ph_larchmere","PHOTOS"),
                N("salem","SPLIT",ba=True), O("carousel"), O("low-qual")],
         cap="Row 2 is now branded. The two weakest old posts quietly archived (recoverable), count still climbs."),
    dict(tag="WEEK 8", count="69 posts", tone="go",
         tiles=[N("longform1","FILM",pin=True), N("reel2","PORTFOLIO",pin=True), N("riverst_cap",pin=True,ba=True),
                N("ph_clevehts","PHOTOS"), N("eaststjoe",ba=True), N("ph_larchmere","PHOTOS"),
                N("salem","SPLIT",ba=True), N("ph_mead","PHOTOS"), N("larchmere","SHOWCASE")],
         cap="Top three rows fully branded. Remaining old posts archived or being reformatted into the template."),
    dict(tag="WEEK 12", count="75 posts", tone="done",
         tiles=[N("longform1","FILM",pin=True), N("reel2","PORTFOLIO",pin=True), N("riverst_cap",pin=True,ba=True),
                N("eaststjoe_cap","INSIDE"), N("ph_secondchance","MISSION"), N("eaststjoe",ba=True),
                N("ph_clevehts","PHOTOS"), N("ph_westside"), N("larchmere","SHOWCASE")],
         cap="One operation, top to bottom. Reformatted classics re-posted as fresh branded content, post count higher than where we started."),
]

def week_html(w):
    tiles = "".join(mini_tile(t) for t in w["tiles"])
    return f'''<div class="wcol">
      <div class="whead wtone-{w['tone']}"><b>{w['tag']}</b><span>{w['count']}</span></div>
      <div class="mgrid">{tiles}</div>
      <p class="wcap">{w['cap']}</p>
    </div>'''

WEEKSTRIP = "\n".join(week_html(w) for w in WEEKS)

HTML = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>@shavitness, Instagram Remodel</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
<style>
:root{{
  --canvas:#000;--soft:#0d0d0d;--card:#141414;--elev:#1e1e1e;
  --hair:#2c2c2c;--hair2:#3c3c3c;
  --ink:#fff;--body:#cfcfcf;--muted:#8a8a8a;
  --brass:#B08D57;--gold:#FFC000;
  --font:'Inter',-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;
}}
*{{box-sizing:border-box;margin:0;padding:0}}
html{{scroll-behavior:smooth}}
body{{background:#050505;color:var(--body);font-family:var(--font);font-weight:300;line-height:1.55;
  -webkit-font-smoothing:antialiased;background-image:radial-gradient(1200px 600px at 80% -10%,rgba(176,141,87,.10),transparent 60%),radial-gradient(900px 500px at 0% 20%,rgba(255,192,0,.05),transparent 55%);}}
.wrap{{max-width:1180px;margin:0 auto;padding:0 24px}}
h1,h2,h3,h4,.disp{{font-family:var(--font);font-weight:800;color:var(--ink);text-transform:uppercase;letter-spacing:-.5px;line-height:1.02}}
.kicker{{font-weight:700;font-size:12px;letter-spacing:2.5px;text-transform:uppercase;color:var(--brass)}}
.stripe{{height:3px;width:56px;background:var(--brass);display:block;border-radius:2px}}
a{{color:var(--gold);text-decoration:none}}
.mut{{color:var(--muted)}}.gold{{color:var(--gold)}}.brass{{color:var(--brass)}}.white{{color:var(--ink)}}

/* embedded images (once each) */
[class*="bg-"]{{background-size:cover;background-position:center}}
{CSS_IMG}

/* ---------- masthead ---------- */
.mast{{padding:64px 0 30px;border-bottom:1px solid var(--hair)}}
.mast .kicker{{margin-bottom:16px}}
.mast h1{{font-size:clamp(34px,6vw,68px);margin:8px 0 14px}}
.mast p.lede{{max-width:720px;font-size:17px;color:var(--body)}}
.mast .meta{{margin-top:22px;display:flex;gap:10px;flex-wrap:wrap}}
.chip{{font-size:12px;letter-spacing:1px;text-transform:uppercase;font-weight:600;color:var(--body);
  border:1px solid var(--hair2);border-radius:999px;padding:7px 14px;background:rgba(255,255,255,.02)}}
.chip b{{color:var(--gold);font-weight:700}}
.cover-foot{{display:none}}

/* ---------- section frame ---------- */
section{{padding:60px 0;border-bottom:1px solid var(--hair)}}
.sec-head{{margin-bottom:34px}}
.sec-head h2{{font-size:clamp(24px,3.4vw,38px);margin:12px 0 10px}}
.sec-head p{{max-width:780px;color:var(--body)}}
.num{{font-family:var(--font);font-weight:800;color:var(--brass);font-size:13px;letter-spacing:2px}}

/* ---------- phone mockup ---------- */
.stage{{display:grid;grid-template-columns:390px 1fr;gap:54px;align-items:start}}
@media(max-width:900px){{.stage{{grid-template-columns:1fr}}}}
.phone{{width:390px;max-width:100%;background:#000;border:10px solid #1c1c1c;border-radius:44px;
  box-shadow:0 40px 90px rgba(0,0,0,.7),0 0 0 1px #000, inset 0 0 0 2px #0a0a0a;overflow:hidden;position:sticky;top:20px}}
.notch{{height:34px;background:#000;display:flex;align-items:center;justify-content:space-between;padding:0 22px 0 26px;font-size:12px;color:#fff;font-weight:600}}
.notch .dot{{width:64px;height:18px;background:#000;border-radius:0 0 14px 14px}}
.ig{{background:#000;color:#fff;font-size:14px}}
.ig-top{{display:flex;align-items:center;justify-content:space-between;padding:8px 14px 10px}}
.ig-top .handle{{display:flex;align-items:center;gap:5px;font-weight:700;font-size:17px}}
.verified{{width:15px;height:15px;display:inline-block}}
.ig-top .ic{{font-size:19px;color:#fff;opacity:.95}}
.ig-head{{display:flex;align-items:center;gap:22px;padding:4px 16px 0}}
.ava{{width:86px;height:86px;border-radius:50%;background-position:center 25%;border:2px solid #000;box-shadow:0 0 0 2px var(--brass)}}
.stats{{display:flex;flex:1;justify-content:space-around;text-align:center}}
.stats b{{display:block;font-size:17px;font-weight:700;color:#fff}}
.stats span{{font-size:12.5px;color:#c7c7c7}}
.ig-bio{{padding:12px 16px 4px;font-size:13.5px;line-height:1.5;color:#f2f2f2}}
.ig-bio .nm{{font-weight:700;color:#fff}}
.ig-bio .cat{{color:#9a9a9a;font-size:12.5px}}
.ig-bio .lk{{color:#c9a15a;font-weight:600}}
.ig-btns{{display:flex;gap:6px;padding:12px 16px 6px}}
.ig-btns button{{flex:1;border:0;border-radius:9px;padding:8px 0;font-size:13px;font-weight:700;font-family:var(--font);cursor:default}}
.b-follow{{background:#c9a15a;color:#111}}
.b-msg{{background:#262626;color:#fff}}
.b-ct{{background:#262626;color:#fff;flex:0 0 42px !important}}
.phl-row{{display:flex;gap:15px;padding:14px 16px 8px;overflow-x:auto}}
.phl{{display:flex;flex-direction:column;align-items:center;gap:6px;flex:0 0 auto;width:62px}}
.phl-ring{{width:58px;height:58px;border-radius:50%;padding:2px;background:linear-gradient(135deg,var(--brass),#5c4a2c);display:block}}
.phl-cover{{display:block;width:100%;height:100%;border-radius:50%;border:2px solid #000}}
.phl-label{{font-size:10.5px;color:#e0e0e0;text-align:center;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:62px}}
.tabs{{display:flex;border-top:1px solid #222;margin-top:8px}}
.tabs span{{flex:1;text-align:center;padding:9px 0;color:#8a8a8a;font-size:18px}}
.tabs .on{{color:#fff;border-top:1.5px solid #fff;margin-top:-1px}}
.pgrid{{display:grid;grid-template-columns:repeat(3,1fr);gap:2px;background:#000}}
.tile{{position:relative;aspect-ratio:3/4;overflow:hidden}}
.tile figcaption{{position:absolute;inset:auto 0 0 0;font-size:8.5px;line-height:1.25;color:#fff;
  padding:14px 5px 5px;background:linear-gradient(transparent,rgba(0,0,0,.82));opacity:0;transition:.2s}}
.tile:hover figcaption{{opacity:1}}
.ticon{{position:absolute;top:5px;right:5px;filter:drop-shadow(0 1px 2px rgba(0,0,0,.6))}}
.pin{{position:absolute;top:4px;left:5px;font-size:12px;filter:drop-shadow(0 1px 2px #000)}}
.tbadge{{position:absolute;top:6px;left:22px;font-size:8px;font-weight:800;letter-spacing:.6px;color:#111;
  background:var(--gold);padding:2px 5px;border-radius:3px;text-transform:uppercase}}
.ba{{position:absolute;bottom:6px;left:6px;font-size:8px;font-weight:800;letter-spacing:.7px;color:#fff;
  background:rgba(176,141,87,.92);padding:2px 6px;border-radius:3px}}

/* annotations */
.notes{{display:flex;flex-direction:column;gap:14px}}
.note{{background:linear-gradient(180deg,var(--card),#0e0e0e);border:1px solid var(--hair);border-left:3px solid var(--brass);border-radius:10px;padding:16px 18px}}
.note h4{{font-size:14px;letter-spacing:.4px;text-transform:none;margin-bottom:6px;color:#fff;display:flex;align-items:center;gap:9px}}
.note .tag{{font-size:10px;font-weight:800;letter-spacing:1px;color:#111;background:var(--gold);border-radius:4px;padding:3px 7px;text-transform:uppercase}}
.note p{{font-size:13.5px;color:var(--body)}}
.note .ba-note{{color:var(--muted);font-size:12px;margin-top:6px}}
.note .ba-note b{{color:#e0e0e0}}

/* transition timeline */
.tl{{display:grid;grid-template-columns:repeat(4,1fr);gap:16px}}
@media(max-width:820px){{.tl{{grid-template-columns:1fr 1fr}}}}
@media(max-width:480px){{.tl{{grid-template-columns:1fr}}}}
.tl-step{{background:linear-gradient(180deg,var(--card),#0d0d0d);border:1px solid var(--hair);border-top:3px solid var(--brass);border-radius:12px;padding:20px}}
.tl-badge{{display:inline-block;font-size:11px;font-weight:800;letter-spacing:1.5px;color:#111;background:var(--gold);border-radius:5px;padding:4px 10px;margin-bottom:12px}}
.tl-step h4{{font-size:15px;text-transform:none;color:#fff;margin-bottom:8px;letter-spacing:0}}
.tl-step p{{font-size:13px;color:var(--body)}}
.mini{{font-size:16px;text-transform:uppercase;letter-spacing:.5px;color:#fff;margin:40px 0 16px}}
.rule-grid{{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}}
@media(max-width:820px){{.rule-grid{{grid-template-columns:1fr 1fr}}}}
@media(max-width:480px){{.rule-grid{{grid-template-columns:1fr}}}}
.rule{{background:var(--soft);border:1px solid var(--hair);border-radius:12px;padding:18px}}
.rule .rlbl{{font-size:13px;font-weight:800;letter-spacing:.5px;margin-bottom:8px}}
.rule.keep{{border-left:3px solid #0fa336}}.rule.keep .rlbl{{color:#3ad46a}}
.rule.reformat{{border-left:3px solid var(--gold)}}.rule.reformat .rlbl{{color:var(--gold)}}
.rule.archive{{border-left:3px solid var(--muted)}}.rule.archive .rlbl{{color:#b7b7b7}}
.rule.rehome{{border-left:3px solid var(--brass)}}.rule.rehome .rlbl{{color:var(--brass)}}
.rule p{{font-size:12.5px;color:var(--body)}}

/* week-by-week strip */
.wstrip{{display:grid;grid-template-columns:repeat(5,1fr);gap:14px}}
@media(max-width:980px){{.wstrip{{display:flex;overflow-x:auto;scroll-snap-type:x mandatory;padding-bottom:10px}}
  .wcol{{flex:0 0 240px;scroll-snap-align:start}}}}
.wcol{{background:var(--soft);border:1px solid var(--hair);border-radius:12px;padding:12px;display:flex;flex-direction:column}}
.whead{{display:flex;align-items:center;justify-content:space-between;padding:4px 6px 10px}}
.whead b{{font-size:13px;font-weight:800;letter-spacing:1px;color:#fff}}
.whead span{{font-size:11px;color:var(--muted)}}
.wtone-now b{{color:var(--muted)}}
.wtone-go b{{color:var(--gold)}}
.wtone-done b{{color:#3ad46a}}
.mgrid{{display:grid;grid-template-columns:repeat(3,1fr);gap:2px;background:#000;border-radius:6px;overflow:hidden}}
.mtile{{position:relative;aspect-ratio:1/1;overflow:hidden;display:block}}
.mold{{background:repeating-linear-gradient(45deg,#141414 0 7px,#181818 7px 14px);display:flex;align-items:center;justify-content:center}}
.moldlab{{font-size:7.5px;letter-spacing:.3px;color:#6f6f6f;text-align:center;padding:2px;text-transform:uppercase;font-weight:600}}
.mpin{{position:absolute;top:2px;left:3px;font-size:9px;z-index:2;filter:drop-shadow(0 1px 1px #000)}}
.mbadge{{position:absolute;bottom:3px;left:3px;right:3px;font-size:6.5px;font-weight:800;letter-spacing:.3px;color:#111;background:var(--gold);padding:1px 0;border-radius:2px;text-align:center;text-transform:uppercase}}
.mba{{position:absolute;top:3px;right:3px;width:8px;height:8px;border-radius:2px;background:var(--brass);box-shadow:0 0 0 1px rgba(0,0,0,.4)}}
.wcap{{font-size:11.5px;color:var(--body);margin-top:12px;line-height:1.45}}

/* bio before/after */
.compare{{display:grid;grid-template-columns:1fr 1fr;gap:18px}}
@media(max-width:720px){{.compare{{grid-template-columns:1fr}}}}
.cbox{{border:1px solid var(--hair);border-radius:12px;padding:20px;background:var(--soft)}}
.cbox.after{{border-color:var(--brass);box-shadow:0 0 0 1px rgba(176,141,87,.25)}}
.cbox .lbl{{font-size:11px;font-weight:800;letter-spacing:2px;text-transform:uppercase;margin-bottom:12px}}
.cbox.before .lbl{{color:var(--muted)}}.cbox.after .lbl{{color:var(--gold)}}
.biocode{{font-size:14px;line-height:1.7;color:#eee;white-space:pre-wrap;font-weight:300}}
.biocode.dim{{color:#9a9a9a}}
.cbox small{{display:block;margin-top:12px;color:var(--muted);font-size:12px}}

/* cross-platform cards */
.plat-grid{{display:grid;gap:18px}}
.pcard{{border:1px solid var(--hair);border-radius:14px;padding:20px 22px;background:var(--soft)}}
.pcard-head{{display:flex;align-items:center;gap:14px;margin-bottom:16px}}
.picon{{width:38px;height:38px;border-radius:9px;display:flex;align-items:center;justify-content:center;font-weight:800;font-size:16px;color:#fff;flex:0 0 auto}}
.pcard-id{{display:flex;flex-direction:column;line-height:1.3}}
.pcard-id b{{color:#fff;font-size:16px}}
.purl{{color:var(--muted);font-size:12px;letter-spacing:.3px}}
.prole{{margin-left:auto;font-size:11px;font-weight:800;letter-spacing:1.5px;text-transform:uppercase;color:var(--gold);border:1px solid rgba(255,192,0,.35);border-radius:999px;padding:5px 12px;white-space:nowrap}}
.pcompare{{display:grid;grid-template-columns:1fr 1fr;gap:14px}}
@media(max-width:720px){{.pcompare{{grid-template-columns:1fr}}}}
.pbox{{border:1px solid var(--hair);border-radius:10px;padding:14px 16px;background:#0b0b0b}}
.pbox.prev{{border-color:var(--brass);box-shadow:0 0 0 1px rgba(176,141,87,.22)}}
.plbl{{font-size:10px;font-weight:800;letter-spacing:2px;text-transform:uppercase;margin-bottom:9px}}
.pnow .plbl{{color:var(--muted)}}.prev .plbl{{color:var(--gold)}}
.pcode{{font-size:12.5px;line-height:1.6;color:#e9e9e9;white-space:pre-wrap;font-weight:300}}
.pnow .pcode{{color:#9a9a9a}}
.pnote{{margin:14px 0 0;font-size:12.5px;line-height:1.6;color:var(--body)}}

/* ---- per-platform phone mockups ---- */
.pstage{{display:grid;grid-template-columns:390px 1fr;gap:54px;align-items:start;margin:0 0 60px}}
@media(max-width:900px){{.pstage{{grid-template-columns:1fr;gap:30px}}}}
.pstage .notes{{padding-top:6px}}
.mock{{color:#fff;font-size:14px;background:#000}}
.m-cover{{height:132px;background-size:cover;background-position:left center;position:relative}}
.m-cover::after{{content:"";position:absolute;inset:0;background:linear-gradient(180deg,rgba(0,0,0,.05),rgba(0,0,0,.65))}}
.m-ava{{width:82px;height:82px;border-radius:50%;background-size:cover;background-position:center 25%;border:3px solid #000;margin:-42px 0 0 18px;position:relative;z-index:2;box-shadow:0 0 0 2px var(--brass)}}
.m-body{{padding:8px 18px 18px}}
.m-name{{font-size:19px;font-weight:800;display:flex;align-items:center;gap:6px}}
.m-sub{{color:#9a9a9a;font-size:12.5px;margin-top:2px}}
.m-meta{{color:#c7c7c7;font-size:12.5px;margin-top:6px}}
.m-btns{{display:flex;gap:6px;margin:14px 0 4px}}
.m-btns button{{flex:1;border:0;border-radius:8px;padding:9px 0;font-size:13px;font-weight:700;font-family:var(--font);cursor:default;color:#fff}}
.m-btns .ghost{{background:#2a2a2a}}
.m-card{{background:#111;border:1px solid #232323;border-radius:11px;padding:13px 15px;margin-top:14px;font-size:13px;line-height:1.55;color:#eaeaea;white-space:pre-wrap}}
.m-card .h{{font-size:10.5px;font-weight:800;letter-spacing:1.6px;text-transform:uppercase;color:#8a8a8a;margin-bottom:8px}}
.m-lk{{color:#c9a15a;font-weight:600}}
.m-tabs{{display:flex;border-top:1px solid #222;border-bottom:1px solid #222;margin-top:16px}}
.m-tabs span{{flex:1;text-align:center;padding:10px 0;color:#8a8a8a;font-size:12.5px;font-weight:600}}
.m-tabs .on{{color:#fff;border-bottom:2px solid var(--gold);margin-bottom:-1px}}
.m-pin{{display:flex;gap:11px;align-items:center;margin-top:14px}}
.m-thumb{{width:66px;height:66px;border-radius:8px;background-size:cover;background-position:center;flex:0 0 auto}}
.m-pin .t{{font-size:12.5px;line-height:1.4}}
.m-pin .t b{{color:#fff}}.m-pin .t span{{color:#8a8a8a}}
.m-feat{{display:flex;gap:9px;margin-top:12px}}
.m-feat .f{{flex:1;height:74px;border-radius:8px;background-size:cover;background-position:center;position:relative}}
.m-feat .f span{{position:absolute;left:6px;bottom:6px;font-size:10px;font-weight:700;background:rgba(0,0,0,.6);padding:2px 6px;border-radius:5px}}
/* substack list */
.sub-mast{{text-align:center;padding:20px 18px 4px}}
.sub-logo{{width:44px;height:44px;border-radius:9px;background-size:cover;margin:0 auto 10px;box-shadow:0 0 0 2px var(--brass)}}
.sub-title{{font-size:18px;font-weight:800}}
.sub-desc{{color:#9a9a9a;font-size:12.5px;margin-top:4px;padding:0 6px}}
.sub-btn{{background:#FF6719;color:#fff;border:0;border-radius:7px;padding:9px 20px;font-weight:800;font-size:13px;font-family:var(--font);margin-top:12px;cursor:default}}
.sub-nav{{display:flex;justify-content:center;gap:20px;border-top:1px solid #222;border-bottom:1px solid #222;margin-top:16px;padding:9px 0;color:#8a8a8a;font-size:12px;font-weight:600}}
.sub-post{{display:flex;gap:12px;padding:14px 18px;border-bottom:1px solid #1a1a1a}}
.sub-post .body{{flex:1}}
.sub-post .ttl{{font-weight:800;font-size:13.5px;line-height:1.35}}
.sub-post .dek{{color:#9a9a9a;font-size:12px;margin-top:3px;line-height:1.4}}
.sub-post .dt{{color:#6f6f6f;font-size:11px;margin-top:6px}}
.sub-post .th{{width:64px;height:64px;border-radius:7px;background-size:cover;background-position:center;flex:0 0 auto}}
/* meta business suite dashboard */
.mbs{{padding:16px 16px 20px}}
.mbs-h{{display:flex;align-items:center;gap:9px;font-weight:800;font-size:15px;margin-bottom:4px}}
.mbs-h .g{{width:22px;height:22px;border-radius:6px;background:var(--gold);color:#000;display:flex;align-items:center;justify-content:center;font-size:13px}}
.mbs-conn{{display:flex;gap:7px;margin:12px 0}}
.mbs-chip{{font-size:11px;font-weight:700;background:#161616;border:1px solid #262626;border-radius:999px;padding:5px 11px;color:#dcdcdc}}
.mbs-lbl{{font-size:10px;font-weight:800;letter-spacing:1.4px;text-transform:uppercase;color:#8a8a8a;margin:14px 0 8px}}
.mbs-row{{display:flex;align-items:center;gap:10px;background:#111;border:1px solid #232323;border-radius:9px;padding:9px 11px;margin-bottom:7px}}
.mbs-row .th{{width:38px;height:38px;border-radius:6px;background-size:cover;background-position:center;flex:0 0 auto}}
.mbs-row .mid{{flex:1;font-size:12px}}.mbs-row .mid b{{color:#fff}}.mbs-row .mid span{{color:#8a8a8a;display:block;font-size:11px}}
.mbs-row .st{{font-size:10px;font-weight:800;color:#4ea1ff;background:rgba(78,161,255,.12);padding:3px 8px;border-radius:6px}}
.mbs-kpi{{display:flex;gap:8px;margin-top:12px}}
.mbs-kpi div{{flex:1;background:#111;border:1px solid #232323;border-radius:9px;padding:10px;text-align:center}}
.mbs-kpi b{{display:block;font-size:15px;color:#fff}}.mbs-kpi span{{font-size:10px;color:#8a8a8a}}
/* youtube channel */
.yt-subbtn{{background:#FF0000;color:#fff;border:0;border-radius:999px;padding:9px 22px;font-weight:800;font-size:13px;font-family:var(--font);margin-top:12px;cursor:default}}
.yt-grid{{display:grid;grid-template-columns:1fr 1fr;gap:11px;padding:14px 16px 18px}}
.yt-vid .thm{{position:relative;height:80px;border-radius:8px;background-size:cover;background-position:center}}
.yt-vid .dur{{position:absolute;right:5px;bottom:5px;background:rgba(0,0,0,.85);font-size:9px;font-weight:700;padding:1px 5px;border-radius:3px;color:#fff}}
.yt-vid .vt{{font-size:11.5px;font-weight:600;margin-top:7px;line-height:1.32}}
.yt-vid .vm{{font-size:10px;color:#8a8a8a;margin-top:2px}}
/* single IG post preview (the first drafted post) */
.postwrap{{display:grid;grid-template-columns:390px 1fr;gap:54px;align-items:start;margin-top:14px}}
@media(max-width:900px){{.postwrap{{grid-template-columns:1fr;gap:30px}}}}
.igp-top{{display:flex;align-items:center;gap:10px;padding:11px 14px}}
.igp-top .a{{width:34px;height:34px;border-radius:50%;background-size:cover;background-position:center 25%;box-shadow:0 0 0 2px var(--brass);flex:0 0 auto}}
.igp-top .h{{font-weight:700;font-size:14px;display:flex;align-items:center;gap:4px;color:#fff}}
.igp-img{{height:300px;background-size:cover;background-position:center;position:relative}}
.igp-img .reel{{position:absolute;right:10px;top:9px;font-size:17px}}
.igp-img .ba{{position:absolute;left:10px;bottom:10px;background:rgba(176,141,87,.92);color:#111;font-size:10px;font-weight:800;letter-spacing:1px;padding:3px 9px;border-radius:6px}}
.igp-act{{display:flex;gap:16px;padding:11px 14px 3px;font-size:20px;color:#fff}}
.igp-act .r{{margin-left:auto}}
.igp-likes{{padding:0 14px;font-weight:700;font-size:13px;color:#fff}}
.igp-cap{{padding:6px 14px 15px;font-size:13px;line-height:1.55;white-space:pre-wrap;color:#f2f2f2}}
.igp-cap b{{font-weight:700;color:#fff}}
.ptime{{display:flex;align-items:flex-start;gap:9px;background:rgba(255,192,0,.1);border:1px solid rgba(255,192,0,.4);border-radius:10px;padding:12px 14px;font-size:12.5px;color:#f0e2bf;line-height:1.5;margin-top:2px}}
.ptime b{{color:#ffd94a}}
/* rebrand announcement posts */
.anncols{{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin-top:14px}}
@media(max-width:820px){{.anncols{{grid-template-columns:1fr}}}}
.anncard{{border:1px solid var(--hair);border-radius:14px;background:var(--soft);overflow:hidden}}
.ann-head{{display:flex;align-items:center;gap:11px;padding:14px 17px;font-weight:800;font-size:14px;color:#fff;border-bottom:1px solid var(--hair)}}
.ann-head .i{{width:30px;height:30px;border-radius:7px;display:flex;align-items:center;justify-content:center;font-weight:800;font-size:15px;color:#fff;flex:0 0 auto}}
.ann-head small{{display:block;font-weight:500;font-size:11px;color:#9a9a9a}}
.ann-body{{padding:14px 18px 18px;font-size:13px;line-height:1.62;white-space:pre-wrap;color:#eaeaea}}

/* highlight cards */
.hl-grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:18px}}
.hl{{background:var(--soft);border:1px solid var(--hair);border-radius:12px;padding:20px;text-align:center}}
.hl-ring{{width:82px;height:82px;margin:0 auto 12px;border-radius:50%;padding:3px;background:linear-gradient(135deg,var(--brass),#4a3a22)}}
.hl-cover{{display:block;width:100%;height:100%;border-radius:50%;border:2px solid var(--soft)}}
.hl-name{{font-weight:800;letter-spacing:1px;font-size:13px;color:#fff;text-transform:uppercase;margin-bottom:8px}}
.hl-desc{{font-size:12.5px;color:var(--body)}}

/* cadence table */
.cal{{width:100%;border-collapse:collapse;font-size:13.5px}}
.cal th,.cal td{{text-align:left;padding:12px 14px;border-bottom:1px solid var(--hair)}}
.cal th{{font-size:11px;letter-spacing:1.5px;text-transform:uppercase;color:var(--brass);font-weight:800}}
.cal td b{{color:#fff;font-weight:600}}
.cal .wk{{color:var(--gold);font-weight:800;white-space:nowrap}}
.cal tr:hover td{{background:rgba(255,255,255,.02)}}

/* pillars */
.pill-grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:16px}}
.pill{{background:linear-gradient(180deg,var(--card),#0d0d0d);border:1px solid var(--hair);border-radius:12px;padding:20px;position:relative;overflow:hidden}}
.pill .pct{{position:absolute;top:14px;right:16px;font-weight:800;font-size:26px;color:rgba(255,192,0,.16)}}
.pill h4{{font-size:15px;text-transform:none;margin-bottom:8px;color:#fff}}
.pill p{{font-size:13px;color:var(--body)}}
.pill .bar{{height:5px;border-radius:3px;background:#222;margin-top:14px;overflow:hidden}}
.pill .bar i{{display:block;height:100%;background:linear-gradient(90deg,var(--brass),var(--gold))}}

/* kpi */
.kpi-grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:16px}}
.kpi{{background:var(--soft);border:1px solid var(--hair);border-radius:12px;padding:20px}}
.kpi .k{{font-size:11px;letter-spacing:1.5px;text-transform:uppercase;color:var(--brass);font-weight:800}}
.kpi .v{{font-size:19px;font-weight:800;color:#fff;margin:8px 0 6px;text-transform:none;letter-spacing:0}}
.kpi p{{font-size:12.5px;color:var(--body)}}
.callout{{background:rgba(176,141,87,.08);border:1px solid rgba(176,141,87,.35);border-radius:10px;padding:14px 18px;margin-top:20px;font-size:13px;color:#e6dcc9}}

/* next */
.steps{{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:16px}}
.step{{background:linear-gradient(180deg,var(--card),#0d0d0d);border:1px solid var(--hair);border-radius:12px;padding:20px}}
.step .n{{width:30px;height:30px;border-radius:50%;background:var(--gold);color:#111;font-weight:800;display:flex;align-items:center;justify-content:center;margin-bottom:12px}}
.step h4{{font-size:14px;text-transform:none;margin-bottom:6px;color:#fff}}
.step p{{font-size:13px;color:var(--body)}}

footer{{padding:44px 0 70px;color:var(--muted);font-size:12.5px}}
footer .stripe{{margin-bottom:18px}}
.legend{{display:flex;gap:18px;flex-wrap:wrap;margin-top:16px;font-size:12px;color:var(--muted)}}
.legend span{{display:flex;align-items:center;gap:7px}}
.sw{{width:14px;height:14px;border-radius:3px;display:inline-block}}

/* ---------- print / PDF ---------- */
@media print{{
  @page{{ size:1120px 1440px; margin:30px 34px; }}
  *{{ -webkit-print-color-adjust:exact !important; print-color-adjust:exact !important; }}
  html,body{{ background:#050505 !important; }}
  body{{ background-image:none !important; }}
  header.mast{{ break-after:page; position:relative; min-height:calc(1440px - 60px);
    display:flex; flex-direction:column; justify-content:center; padding:0; }}
  .cover-foot{{ display:block; position:absolute; left:0; right:0; bottom:8px;
    color:var(--muted); font-size:12.5px; letter-spacing:.3px; }}
  .cover-foot .stripe{{ margin-bottom:14px; }}
  .cover-foot b{{ color:var(--brass); }}
  section{{ border-bottom:0 !important; padding:30px 0; }}
  .sec-head{{ break-after:avoid; break-inside:avoid; }}
  .phone{{ position:static !important; box-shadow:none !important; }}
  .stage,.phone,.notes,.note,.wstrip,.wcol,.tl,.tl-step,.rule-grid,.rule,.pill-grid,.pill,
  .kpi-grid,.kpi,.steps,.step,.cbox,.compare,.hl-grid,.hl,.callout,table{{ break-inside:avoid; }}
  .wstrip{{ display:grid !important; grid-template-columns:repeat(5,1fr) !important; overflow:visible !important; }}
  .phl-row{{ overflow:visible !important; }}
  a{{ color:var(--gold) !important; }}
}}
</style>
</head>
<body>

<header class="mast"><div class="wrap">
  <span class="kicker">Social Media Remodel · Prepared by Jake for Shavit Rootman</span>
  <h1>What your <span class="gold">socials</span><br>become.</h1>
  <p class="lede">You’re already on Instagram, Facebook, LinkedIn and Substack, and every one still reads as the <b class="white">personal</b> Shavit that went quiet in February. This rebuilds all of them, plus a Meta Business Suite cockpit and a YouTube channel to establish, into one <b class="white">real-estate operator brand</b>, using footage and photos we already made, on a calm 2 to 3-post-a-week rhythm. Instagram is the deep-dive (it’s the flagship); Section 02 covers the full footprint. Reputation, not noise.</p>
  <div class="meta">
    <span class="chip"><b>5,054</b>&nbsp;followers to reactivate</span>
    <span class="chip"><b>Verified ✓</b>&nbsp;kept</span>
    <span class="chip">Brand: <b>Live with us. Work with us.</b></span>
    <span class="chip"><b>2-3</b>&nbsp;posts / week</span>
  </div>
</div>
<div class="cover-foot"><span class="stripe"></span>Draft for review · Prepared by Jake Horvitz · <b>Live with us. Work with us.</b> · shavitrootman.com</div>
</header>

<!-- ===== THE MOCKUP ===== -->
<section><div class="wrap">
  <div class="sec-head">
    <span class="num">01 · THE PROFILE</span>
    <h2>Your new profile, at a glance</h2>
    <p>Hover any tile to read what it is. The three 📌 tiles are the pinned first impression. It’s a deliberate <b class="white">mix of reels and house photos</b>, all built from footage and photos that already exist.</p>
  </div>
  <div class="stage">
    <div class="phone">
      <div class="notch"><span>9:41</span><span class="dot"></span><span>&#9679;&#9679;&#9679; &#9207; &#9635;</span></div>
      <div class="ig">
        <div class="ig-top">
          <span class="handle">shavitness
            <svg class="verified" viewBox="0 0 24 24" fill="#3897f0"><path d="M12 1l2.4 2.1 3.2-.3 1.3 2.9 2.9 1.3-.3 3.2L23 12l-2.1 2.4.3 3.2-2.9 1.3-1.3 2.9-3.2-.3L12 23l-2.4-2.1-3.2.3-1.3-2.9L2.2 17l.3-3.2L1 12l2.1-2.4-.3-3.2 2.9-1.3L7 2.2l3.2.3z"/><path d="M10.4 15.3l-3-3 1.3-1.3 1.7 1.7 4-4 1.3 1.3z" fill="#fff"/></svg>
          </span>
          <span class="ic">&#9776;</span>
        </div>
        <div class="ig-head">
          <span class="ava bg-avatar"></span>
          <div class="stats">
            <div><b>57</b><span>posts</span></div>
            <div><b>5,054</b><span>followers</span></div>
            <div><b>1,010</b><span>following</span></div>
          </div>
        </div>
        <div class="ig-bio">
          <div class="nm">Shavit Rootman</div>
          <div class="cat">Property Management Company</div>
          <div style="margin-top:6px">Live with us. Work with us.<br>
          📍 Midwest ᐧ 3 states<br>
          👇 The before and after<br>
          <span class="lk">🔗 shavitrootman.com/links</span></div>
        </div>
        <div class="ig-btns">
          <button class="b-follow">Following</button>
          <button class="b-msg">Message</button>
          <button class="b-ct">✉</button>
        </div>
        <div class="phl-row">{HL_ROW}</div>
        <div class="tabs"><span class="on">&#9638;</span><span>&#9654;</span><span>&#128100;</span></div>
        <div class="pgrid">{GRID}</div>
      </div>
    </div>

    <div class="notes">
      <div class="note"><h4><span class="tag">Bio</span> The tagline leads, the grid explains</h4>
        <p><b class="white">“Live with us. Work with us.”</b> up top, then the proof (Midwest, three states) and an arrow into the before/after grid. Today the bio is a name, two flags and a house emoji, it makes a 5k-follower account look dormant. The link stays on shavitrootman.com.</p></div>
      <div class="note"><h4><span class="tag">Account</span> Switch to a Business account</h4>
        <p>Same handle, same verified check. Unlocks Insights (reach, saves, profile taps), the numbers the scorecard runs on, and the category label + contact button. This is your call, Shavit; it changes nothing a visitor loses.</p></div>
      <div class="note"><h4><span class="tag">Pinned</span> Lead with the brand, not 2023</h4>
        <p>The top row becomes: the <b class="white">brand film</b>, the <b class="white">portfolio reel</b>, and one <b class="white">flagship before/after</b>. The Israel &amp; family posts aren’t deleted, they move into a Highlight (“Roots”), so the human story stays without being the first thing a lender or partner sees.</p></div>
      <div class="note"><h4><span class="tag">Grid</span> A mix of reels and house photos</h4>
        <p>Not an all-video wall. Cinematic <b class="white">reels</b> (▶ icon) sit next to <b class="white">photo carousels</b> of the houses (▣ icon), finished interiors, room-by-room, before/after stills. The variety is what makes it read as a real, lived-in account.</p>
        <p class="ba-note"><b>Legend:</b> 📌 pinned · ▶ reel (video) · ▣ photo carousel · <b>BEFORE · AFTER</b> = transformation · gold badge = format tag.</p></div>
    </div>
  </div>
</div></section>

<!-- ===== EVERY PLATFORM ===== -->
<section><div class="wrap">
  <div class="sec-head"><span class="num">02 · EVERY PLATFORM</span>
    <h2>Not one account, <span class="gold">the whole footprint</span></h2>
    <p>Instagram is the flagship, but you already exist on four platforms, and every one of them still points at the <b class="white">personal</b> Shavit, not the brand. Each is live, each was found and read. Below, each one gets the <b class="white">same mockup treatment</b> as the Instagram profile above, this is what it looks like rebuilt. Same voice everywhere: <b class="white">Live with us. Work with us.</b></p></div>
  {MOCKUPS_HTML}
  <div class="callout" style="margin-top:24px"><b>One link, one order.</b> Every bio points to <b style="color:#ddd">shavitrootman.com/links</b>, a single branded link page (no third-party logo) listing, in this order: <b style="color:#ddd">Website → Facebook → LinkedIn → Substack</b>. Change a destination once, it updates everywhere.</div>
</div></section>

<!-- ===== TRANSITION ===== -->
<section><div class="wrap">
  <div class="sec-head"><span class="num">03 · THE TRANSITION</span>
    <h2>How we revamp <span class="gold">without going blank</span></h2>
    <p>The #1 worry with a rebrand: “do we wipe 57 posts and start from an empty grid?” <b class="white">No.</b> We never delete in bulk, and the account is never blank for a single day. The trick is to <b class="white">layer new on top first, then quietly retire the old</b>, and on Instagram you <b class="white">Archive</b> (hide, fully reversible) rather than delete, so nothing is ever lost.</p></div>

  <div class="tl">
    <div class="tl-step"><div class="tl-badge">DAY 1</div>
      <h4>Reframe, remove nothing</h4>
      <p>Switch to Business, swap the bio, add the 5 highlights, and <b class="white">re-pin the top 3</b>. Every old post still sits there, but the first impression is already the new brand. A 20-minute change that makes the account feel reborn without touching the grid.</p></div>
    <div class="tl-step"><div class="tl-badge">WEEKS 1-4</div>
      <h4>Layer new on top</h4>
      <p>Start posting the branded content, 2-3×/week. New posts land at the top, so the grid <b class="white">fills up and drifts the old stuff down naturally</b>. Post count goes <b class="white">up</b>, never down.</p></div>
    <div class="tl-step"><div class="tl-badge">WEEKS 3-8</div>
      <h4>Quietly retire, matched 1:1</h4>
      <p>As branded rows build, <b class="white">Archive 2-3 weak old posts a week, only as fast as new ones go up</b>. The total count stays flat-to-climbing, the grid is never patchy, and archived posts are recoverable (and re-usable).</p></div>
    <div class="tl-step"><div class="tl-badge">BY WEEK 12</div>
      <h4>One operation, top to bottom</h4>
      <p>The top 3-4 rows are fully branded. Anything below is either archived or intentionally kept. The account reads as one operation, and it was <b class="white">never once blank</b> along the way.</p></div>
  </div>

  <h3 class="mini">Watch the grid, week by week</h3>
  <p style="max-width:820px;margin:-8px 0 22px;color:var(--body)">Left to right: the same account, transforming. New branded posts (gold/brass tiles) fill from the top; the striped tiles are your existing posts, retiring a few at a time. Notice the post count only ever climbs.</p>
  <div class="wstrip">{WEEKSTRIP}</div>

  <h3 class="mini">The keep / reformat / archive rule</h3>
  <div class="rule-grid">
    <div class="rule keep"><div class="rlbl">✓ Keep</div><p>Genuine property before/afters &amp; finished-home carousels. On-brand already, we just reformat them into the template over time.</p></div>
    <div class="rule reformat"><div class="rlbl">♻ Reformat</div><p>Strong stories shot in low quality. Re-edit the good ones into the new template and re-post as fresh content.</p></div>
    <div class="rule archive"><div class="rlbl">⤓ Archive</div><p>Random, off-brand, or low-quality one-offs. Hidden (not deleted), a few a week, only as new posts replace them.</p></div>
    <div class="rule rehome"><div class="rlbl">🇮🇱 Re-home</div><p>The Israel &amp; family posts move into the “Roots” highlight, the human story stays visible without leading the grid.</p></div>
  </div>
  <div class="callout" style="margin-top:24px">Net effect: on any given day a visitor sees a <b>full, on-brand grid</b>. There is no “under construction” phase, the revamp happens live and invisibly, one post at a time.</div>
</div></section>

<!-- ===== BIO ===== -->
<section><div class="wrap">
  <div class="sec-head"><span class="num">04 · THE BIO</span>
    <h2>Before &amp; after: the bio</h2>
    <p>The bio is the one piece of copy every visitor reads. Here’s the swap (kept under Instagram’s 150-character limit).</p></div>
  <div class="compare">
    <div class="cbox before"><div class="lbl">Now</div>
      <div class="biocode dim">שביט רוטמן
🇺🇸 🇮🇱
🏠</div>
      <small>Reads as a personal account. No brand, no proof, no reason for a stranger to follow.</small></div>
    <div class="cbox after"><div class="lbl">Proposed</div>
      <div class="biocode">Live with us. Work with us.
📍 Midwest ᐧ 3 states
👇 The before and after
🔗 shavitrootman.com/links</div>
      <small>Name field: <b style="color:#ddd">Shavit Rootman</b> · Category: <b style="color:#ddd">Property Management Company</b>. The tagline leads; the grid does the explaining. The 🇺🇸🇮🇱 flags move into the “Roots” highlight, the identity is intact, the brand line is now the first thing read.</small></div>
  </div>
</div></section>

<!-- ===== HIGHLIGHTS ===== -->
<section><div class="wrap">
  <div class="sec-head"><span class="num">05 · HIGHLIGHTS</span>
    <h2>Five highlights that do the selling</h2>
    <p>Highlights are the permanent menu under your bio. Five, each with a brass-ringed cover, so a first-time visitor can navigate your whole story in five taps.</p></div>
  <div class="hl-grid">{HL_HTML}</div>
</div></section>

<!-- ===== PILLARS ===== -->
<section><div class="wrap">
  <div class="sec-head"><span class="num">06 · CONTENT PILLARS</span>
    <h2>What we post, and how often</h2>
    <p>Five pillars keep the grid varied without ever guessing what to post. The mix leans on transformations (they get saved and shared the most) while keeping the mission and the human side in frame.</p></div>
  <div class="pill-grid">
    <div class="pill"><span class="pct">40%</span><h4>Transformations</h4><p>Before → after reveals. The signature format and the highest-save content. Two matched photos = one post.</p><div class="bar"><i style="width:40%"></i></div></div>
    <div class="pill"><span class="pct">25%</span><h4>Portfolio &amp; operator POV</h4><p>Reels, walkthroughs, “inside the operation.” Proof of scale: three states, one crew.</p><div class="bar"><i style="width:25%"></i></div></div>
    <div class="pill"><span class="pct">15%</span><h4>The mission</h4><p>Second-chance housing, community, dignity. The reputation layer, why this operation is different.</p><div class="bar"><i style="width:15%"></i></div></div>
    <div class="pill"><span class="pct">10%</span><h4>The human / roots</h4><p>Shavit, the team, Israel, behind-the-scenes. The authenticity your 5k base already follows you for.</p><div class="bar"><i style="width:10%"></i></div></div>
    <div class="pill"><span class="pct">10%</span><h4>Education / market</h4><p>“BRRRR, explained.” “What it cost / what it became.” Quiet authority that ages well.</p><div class="bar"><i style="width:10%"></i></div></div>
  </div>
</div></section>

<!-- ===== CADENCE ===== -->
<section><div class="wrap">
  <div class="sec-head"><span class="num">07 · THE 90-DAY REACTIVATION</span>
    <h2>A calm relaunch, 2-3 posts a week</h2>
    <p>No explosion. A steady reactivation of the base you already have. Weekly template: a transformation early week, a portfolio/education mid-week, and an optional mission/human post to close it out. Light Stories 2-3× a week.</p></div>
  <table class="cal">
    <tr><th>Phase</th><th>Weeks</th><th>What happens</th><th>Anchor posts</th></tr>
    <tr><td class="wk">Relaunch</td><td>1-2</td><td><b>“We’re back, here’s the standard.”</b> Pin the brand film, drop Reel 1, run the first flagship before/after.</td><td>Brand film · Portfolio reel · River Street B/A</td></tr>
    <tr><td class="wk">Rhythm</td><td>3-6</td><td>Lock the weekly cadence and rotate the pillars. Deploy the before/after library one at a time.</td><td>East St. Joe · Larchmere · 61 Salem · Reel 2</td></tr>
    <tr><td class="wk">Compound</td><td>7-12</td><td>Double down on the best-performing format, publish the first mission story, log the first inbound. First monthly “state of the brand” note to you.</td><td>Second-chance story · captioned walk-throughs · collage film</td></tr>
  </table>

  <h3 class="mini">Day 1, the relaunch announcement, drafted</h3>
  <p style="max-width:820px;margin:-8px 0 6px;color:var(--body)">Before the first before/after, one post says out loud that the brand is back and different. Same message on LinkedIn (the operator room) and Facebook (the community), tuned to each. Copy-paste ready.</p>
  <div class="anncols">
    <div class="anncard">
      <div class="ann-head"><span class="i" style="background:#0A66C2">in</span>LinkedIn<small>Shavit Rootman · personal profile</small></div>
      <div class="ann-body">Three years ago I bought a house in the Midwest that everyone told me to walk away from.

Today we operate across three states, Michigan, Ohio, and Indiana, and I have never been prouder of the work.

So it is time the brand caught up to it.

Today I am relaunching Shavit Rootman. New look, one standard, and one line that says everything we believe:

Live with us. Work with us.

We buy what everyone else passed on. We rebuild it to a standard we would live in ourselves. Then we stay and manage it like we intend to keep it, because we do.

Over the next 90 days I am going to show you the work. Every project, before and after, start to finish. The houses that fought us, and the ones that changed a family's year.

Follow along. The best of it is still being built.

Live with us. Work with us.</div>
    </div>
    <div class="anncard">
      <div class="ann-head"><span class="i" style="background:#1877F2">f</span>Facebook<small>Shavit Rootman · Business Page</small></div>
      <div class="ann-body">Something new, and a long time coming.

Today we are relaunching Shavit Rootman.

For years we have quietly done one thing: take homes that were written off and bring them back to life. Homes across three states, rebuilt to a standard we would live in ourselves.

Now the brand finally matches the work. New look, one promise:

Live with us. Work with us.

We buy what everyone else passed on. We rebuild it room by room. And we stay, because a house is only worth what it means to the people who live in it.

Over the next few months we are opening the doors. Every project, before and after, so you can see exactly how it gets done.

Follow the page and come along for the ride. The before is where every good story starts.

Live with us. Work with us.</div>
    </div>
  </div>

  <h3 class="mini">Week 1, the first post, drafted</h3>
  <p style="max-width:820px;margin:-8px 0 6px;color:var(--body)">The relaunch opens on the strongest story you have: River Street. Here is the actual post, caption and all, plus the window to publish it in. This is the template every before/after follows.</p>
  <div class="postwrap">
    <div class="phone">{NOTCH}<div class="mock">
      <div class="igp-top"><span class="a bg-avatar"></span><span class="h">shavitness
        <svg class="verified" viewBox="0 0 24 24" fill="#3897f0" style="width:14px;height:14px"><path d="M12 1l2.4 2.1 3.2-.3 1.3 2.9 2.9 1.3-.3 3.2L23 12l-2.1 2.4.3 3.2-2.9 1.3-1.3 2.9-3.2-.3L12 23l-2.4-2.1-3.2.3-1.3-2.9L2.2 17l.3-3.2L1 12l2.1-2.4-.3-3.2 2.9-1.3L7 2.2l3.2.3z"/><path d="M10.4 15.3l-3-3 1.3-1.3 1.7 1.7 4-4 1.3 1.3z" fill="#fff"/></svg></span></div>
      <div class="igp-img bg-riverst"><span class="reel">🎬</span><span class="ba">BEFORE · AFTER</span></div>
      <div class="igp-act">♡ 💬 ➤<span class="r">🔖</span></div>
      <div class="igp-likes">Liked by adamwade and 214 others</div>
      <div class="igp-cap"><b>shavitness</b> River Street, Hillsdale.

A friend’s dad reached out after his daughter graduated. He remembered how we treat our own homes, and he wanted the same for his. Not to flip it. To have it commemorated.

On paper it wasn’t our best deal. We bought it anyway, and we took the financial step of a full, substantial renovation. Down to the studs, rebuilt room by room, every finish chosen like we were the ones moving in.

Some houses you buy for the numbers. This one we did for the person who trusted us with it.

Swipe for the before.

Live with us. Work with us.</div>
    </div></div>
    <div class="notes">
      <div class="note"><h4><span class="tag">The reel</span> River Street before and after</h4>
        <p>The pinned flagship. A friend’s father asked Shavit to take on the family home after his daughter graduated, wanting it treated the way we treat our own. The purchase was not the strongest deal on paper, so the story <i>is</i> the value: trust repaid with a full rebuild.</p></div>
      <div class="note"><h4><span class="tag">The renovation</span> What the reel shows</h4>
        <p>Taken down to the studs and rebuilt room by room, finishes chosen to a live-in standard, not a flip standard. Matched before and after angles carry the reveal.</p></div>
      <div class="ptime"><span style="font-size:16px">🕛</span><div><b>When to post:</b> Tuesday or Wednesday, <b>12:00 to 12:30 PM ET</b>. That midday lunch scroll is the highest-intent window for this audience. If you miss it, anywhere in the <b>12 to 2 PM</b> range still lands. Not a Monday, not after 9 PM.</div></div>
    </div>
  </div>
</div></section>

<!-- ===== KPIs ===== -->
<section><div class="wrap">
  <div class="sec-head"><span class="num">08 · HOW WE'LL MEASURE IT</span>
    <h2>The numbers this feeds</h2>
    <p>Reputation is the goal, so these are the signals we track, measured over a 6-month window, reported to you monthly. <b class="white">These are targets and method, not promises</b>, real figures start the day the account switches to Business and Insights turn on.</p></div>
  <div class="kpi-grid">
    <div class="kpi"><div class="k">Cadence adherence</div><div class="v">100% of planned posts ship</div><p>The controllable win. A 2-week buffer means the brand never goes quiet again.</p></div>
    <div class="kpi"><div class="k">Engagement rate</div><div class="v">Hold &amp; lift vs today</div><p>Current likes run ~1.6-2.3% of followers. Before/afters carry the highest save rate, lead with them.</p></div>
    <div class="kpi"><div class="k">Saves + shares</div><div class="v">The reputation signal</div><p>Saves &amp; shares matter more than likes for a brand play. Tracked monthly.</p></div>
    <div class="kpi"><div class="k">Reach reactivation</div><div class="v">Lift vs dormant baseline</div><p>Waking the 5,054 base and measuring the climb over 90 days.</p></div>
    <div class="kpi"><div class="k">Inbound logged</div><div class="v">DMs · mentions · “saw your stuff”</div><p>Every inbound screenshotted, the evidence that reputation is actually moving.</p></div>
    <div class="kpi"><div class="k">Followers (net new)</div><div class="v">Secondary</div><p>Nice, not the point. Reputation over raw growth, exactly as we agreed.</p></div>
  </div>
  <div class="callout">Everything here honors the plan we set: <b>maintenance and reputation, not virality</b>. The goal is an account that looks alive, on-brand, and never goes quiet, the two things that actually can’t be faked: taste and reliability.</div>
</div></section>

<!-- ===== NEXT ===== -->
<section><div class="wrap">
  <div class="sec-head"><span class="num">09 · IF YOU LIKE THIS</span>
    <h2>What happens next</h2>
    <p>Nothing changes on your account until you say go. This is a draft for you to react to.</p></div>
  <div class="steps">
    <div class="step"><div class="n">1</div><h4>You react</h4><p>Tell me what lands and what doesn’t, bio wording, which posts get pinned, the highlight names.</p></div>
    <div class="step"><div class="n">2</div><h4>Switch to Business</h4><p>One toggle (your call). Same handle, same check, Insights turn on so we can measure.</p></div>
    <div class="step"><div class="n">3</div><h4>Profile refresh</h4><p>New bio, five highlight covers, re-pin the top three. A 20-minute afternoon.</p></div>
    <div class="step"><div class="n">4</div><h4>Relaunch week</h4><p>Brand film goes up, the schedule starts, and the account is alive again, on autopilot from there.</p></div>
  </div>
</div></section>

<footer><div class="wrap">
  <span class="stripe"></span>
  <p><b style="color:#ddd">Shavit Rootman Social Remodel</b> · Instagram · Facebook · Meta Business Suite · LinkedIn · Substack · YouTube. Draft for review, built from existing footage &amp; photos; no posts published, no account changes made. Brand system mirrors shavitrootman.com (black · brass · gold).</p>
  <div class="legend">
    <span><i class="sw" style="background:#000;border:1px solid #444"></i> Canvas #000</span>
    <span><i class="sw" style="background:#B08D57"></i> Brass #B08D57</span>
    <span><i class="sw" style="background:#FFC000"></i> Gold #FFC000</span>
    <span>Type: Inter</span>
  </div>
</div></footer>

</body></html>"""

OUT.write_text(HTML, encoding="utf-8")
print(f"wrote {OUT} ({len(HTML)//1024} KB)")
